# Check the Discovery documents provided by Okta.
# https://YOUR_OKTA_DOMAIN/oauth2/default/.well-known/openid-configuration

okta_domain=YOUR_OKTA_DOMAIN
okta_authorize_uri=/oauth2/default/v1/authorize
okta_token_uri=/oauth2/default/v1/token
okta_jwks_uri=/oauth2/default/v1/keys
okta_idp_issuer=https://YOUR_OKTA_DOMAIN/oauth2/default

apigee_host=YOUR_APIGEE_HOST
apigee_redirect_uri=/v1/oidc/pkce/callback